schema_version: 1

context:
  version: "0.9.6"

package:
  name: pymseed
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pymseed/pymseed-${{ version }}.tar.gz
  sha256: f1b4b0bac1d4601db68e76bb1973a5e33860c672ff20ee3b2ef030ed796adb67

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
        - cffi
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools >=68.0.0
    - cffi >=2.0.0
  run:
    - python
    - cffi >=2.0.0
    - orjson >=3.11.7

tests:
  - python:
      imports:
        - pymseed
      pip_check: true
  - script:
      - python -c "from pymseed import MS3Record, MS3TraceList"

about:
  summary: A Python package for reading and writing miniSEED formatted data
  homepage: https://github.com/EarthScope/pymseed
  repository: https://github.com/EarthScope/pymseed
  license: Apache-2.0
  license_file:
    - LICENSE
    - cffi_module/libmseed/LICENSE

extra:
  recipe-maintainers:
    - chad-earthscope
